site_name: clm-workflow
site_url: https://amansnama.github.io/clm-workflow/

theme:
  name: "readthedocs"

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - markdown_include.include:
      base_path: .  
      # base path . is the current dir of whichever file calls markdown_include

nav:
  - Home: index.md
  - Workflow Reference:
    - Overview: ./reference/index.md
    - Workflow Design: ./reference/design.md
    - Workflow DFD: ./reference/dfd.md